export const REGISTER__USER = 'REGISTER__USER'
export const ERROR__USER = 'ERROR__USER'
export const LOGIN__USER = 'LOGIN__USER'
export const FIND__EMAIL = 'FIND__EMAIL'
export const FIND__EMAIL__ERROR = 'FIND__EMAIL__ERROR'
export const CHANGE__PASSWORD = 'CHANGE__PASSWORD'
export const GET__ALL__USERS = 'GET__ALL__USERS'
export const GET__ALL__USERS__ERROR = 'GET__ALL__USERS__ERROR'
export const GET__ME = 'GET__ME'
export const GET__ME__ERROR = 'GET__ME__ERROR'

export const GET__USER = 'GET__USER'
export const GET__USER__ERROR = 'GET__USER__ERROR'

export const UPLOAD__PIC = 'UPLOAD__PIC'
export const UPLOAD__PIC__ERROR = 'UPLOAD__PIC__ERROR'
export const LOGOUT = 'LOGOUT'
export const GET__ALART = 'GET__ALART'
export const REMOVE__ALART = 'REMOVE__ALART'
export const EDIT__PROFILE = 'EDIT__PROFILE'
export const EDIT__PROFILE__ERROR = 'EDIT__PROFILE__ERROR'

export const GET__POST = 'GET__POST'
export const GET__POST__ERROR = 'GET__POST__ERROR'

export const GET__MY__POST = 'GET__MY__POST'
export const GET__MY__POST__ERROR = 'GET__MY__POST__ERROR'

export const CREATE__POST = 'CREATE__POST'
export const CREATE__POST__ERROR = 'CREATE__POST__ERROR'
export const ISAUTHENTICATION = 'ISAUTHENTICATION'
export const LIKE__POST = 'LIKE__POST'
export const LIKE__POST__ERROR = 'LIKE__POST__ERROR'
export const COMMNENT__POST = 'COMMNENT__POST'
export const COMMNENT__POST__ERROR = 'COMMNENT__POST__ERROR'
export const COMMNENT__POST__REPLY = 'COMMNENT__POST__REPLY'
export const COMMNENT__POST__REPLY__ERROR = 'COMMNENT__POST__REPLY__ERROR'